<?php
$booksAndImgs = [
    "The Silent Patient" => "",
    "Half of A Yellow Sun" => "https://images.unsplash.com/photo-1631899081999-7aa0d7bd57a4?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "Atomic Habits" => "https://images.unsplash.com/photo-1613520761471-8d5f28e343c0?w=300&h=400&fit=crop",
    "The clear Habit Journal" => "",
    "The Psychology of Money" => "",
    "Same as Ever: A Guide to What Never Changes" => "",
    "The Art of Spending Money: Simple Choices for a Richer Life" => "",
    "Pride and Prejudice" => "",
    "Sense and sensibility" => "",
    "Purple Hibiscus" => "",
    "Half of a Yellow Sun" => "",
    "Americana" => "",
    "Dream Count" => "",
    "Mama's Sleeping Calf" => "",
    "The Thing Around Your Neck" => "",
    "The Book Thief" => "",
    "Confessions of Nairobi Men" => "",
    "The Service Berry" => "",
    "Agony of Eros, Waking the tiger, PsychoCybernetics" => "",
    "Drunk" => "",
    "A brief Assignment" => "",
    "The Girl On The Train" => "",
    "The Song of Achilles" => "",
    "Will (Will Smith) Finding me (Viola Davis)" => "",
    "The Idiot. It's the 4th time I can't understand it" => "",
    "Leaders Eat Last" => "",
];
